### ISSUE TITLE
latest v0.1.0.2 can't play .spc files using Foobar2000 v2.0 beta 19

### ISSUE THREAD

**Issue by supermansaga** [stuerp/foo_input_vgmstream#2]
nor PC98-01 .M files.

Foobar2000 v1.6.4 (32bit) can play back .spc files with vgmstream r1800 and .m files w/ help from foo_input_fmpmd.dll which is downloaded from foo_input_fmpmd_v0.8.0.15 (http://ux.getuploader.com/foobar2000/download/31/foo_input_fmpmd_v0.8.0.15.zip) to C:\Program Files (x86)\foobar2000\components\ and together with PMDWin.dll and WinFMP.dll, the latter two were updated in Dec 2021 by author at http://c60.la.coocan.jp/download.html.

**Comment by stuerp** [comment]
@supermansaga,

I struggle to understand what you intend me to do.

* It does work? Or doesn't it?
* Why would vgmstream needs a separate dll.
* Do you have examples of files that don't work?

**Comment by supermansaga** [comment]
@stuerp Hi there, I have been hoping against hope that there is a non-Japanese solution to playing back these Japanese music in .M extension using foobar 2000 v2.0 beta 19. Here are the music files. https://www.dropbox.com/s/0jqp8v28e7qx52v/Lakers%20music.zip?dl=0

The current way to playing them back using Foobar2000 v1.6.14 is one needs to put foo_input_fmpmd.dll from foo_input_fmpmd_v0.8.0.15 (http://ux.getuploader.com/foobar2000/download/31/foo_input_fmpmd_v0.8.0.15.zip) to C:\Program Files (x86)\foobar2000\components\ together with PMDWin.dll and WinFMP.dll, the latter two were updated in Dec 2021 by author at http://c60.la.coocan.jp/download.html.

**Comment by stuerp** [comment]
@supermansaga,

I'll have a look at it but have you tried contacting the vgmstream people? They're specialized in this kind of work. foo_input_vgmstream is simply a wrapper around their library.

**Comment by supermansaga** [comment]
Yes, but neither .spc nor .M are supported formats per https://vgmstream.org/formats. I have been told, "Sequenced music is out of the scope of the vgmstream project. Anything which would use a sequence of note commands with a synthesizer to produce output. VGMStream specializes in streams, which are pre-recorded music which may at most be in some compressed format, but the only synthesis is normal decompression, like MP3 or AAC audio, or ADPCM, or even raw PCM. Vorbis is also a popular choice for streamed game music."

**Comment by stuerp** [comment]
Don't get your hopes up but I have a working prototype outside foobar2000.

**Comment by supermansaga** [comment]
> Don't get your hopes up but I have a working prototype outside foobar2000.

Sure. I have been hoping against hope anyways. And there is nothing false about hope. But what do you mean by "outside foobar 2000"? Isn't the goal to use it with Foobar2000 so that it's a one-stop solution? I don't want to go back to Winamp or any other players unless they are really good and function like a Swiss Army Knife. Many thanks for looking into it.

**Comment by supermansaga** [comment]
> Don't get your hopes up but I have a working prototype outside foobar2000.

Sure. I have been hoping against hope anyways. And there is nothing false about hope. But what do you mean by "outside foobar 2000"? Isn't the goal to use it with Foobar2000 so that it's a one-stop solution? I don't want to go back to Winamp or any other players unless they are really good and function like a Swiss Army Knife.

**Comment by stuerp** [comment]
It just means that I have something running, decoding and playing .m files in a small test program. It would not be worth creating all the foobar code if I ended up with something that does not play.
pmdwin.dll is still required but it compiles as part of the test code. Maybe I'll embed it in the component so that a separate library is not required.
I don't have a clue what winfmp.dll is for. It's not required to play any of the files I found.
I only found .m files but not any .spc files.

**Comment by supermansaga** [comment]
Gotcha. I only uploaded .m files to avoid distracting you, as I presume .Spc is being worked on by someone else at somewhere else that I can't pinpoint. You can see what the dll is for at the author's Japanese site via browser translation. But if not, it is what it is. I can certain upload .spc files if you prefer to kill two birds with one stone. I tend to think nobody in the English speaking world. How do you like the .m files? Ain't the music good in a sense even without playing the game? Thanks

**Comment by supermansaga** [comment]
Accidentally closed prematurely.

**Comment by supermansaga** [comment]
https://www.dropbox.com/s/cnwxxwp4ro9uw1e/KOEI%20SPC.zip?dl=0 Here are the .spc music files. You can play them back with foobar2000 1.6.14 using the component call Game Emu Player at https://www.foobar2000.org/components/view/foo_gep. Would like foobar2000 v2.0 beta 19 x64 to play them back as well. Many thanks

**Comment by stuerp** [comment]
I'm going to close this issue since it has nothing to do with this component.
